# Generated by Django 4.2.6 on 2024-04-28 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Perempuan'), (1, 'Laki-laki')])),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('is_verified', models.BooleanField()),
                ('kota_asal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal_rilis', models.DateField()),
                ('tahun', models.IntegerField()),
                ('durasi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('jenis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik_hak_cipta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_royalti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Songwriter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_Akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.akun')),
                ('id_Pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.pemilik_hak_cipta')),
            ],
        ),
        migrations.CreateModel(
            name='User_playlist',
            fields=[
                ('id_User_playlist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('jumlah_lagu', models.IntegerField(default=0)),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
                ('total_durasi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_Konten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_playlist.konten')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NonPremium',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_playlist.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_playlist.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_playlist.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_dimulai', models.DateTimeField()),
                ('timestamp_berakhir', models.DateTimeField()),
                ('metode_bayar', models.CharField(max_length=50)),
                ('nominal', models.IntegerField()),
                ('email_Akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.akun')),
                ('jenis_Paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=50)),
                ('id_Pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.pemilik_hak_cipta')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('tipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_Akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.akun')),
                ('id_Pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.pemilik_hak_cipta')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('jumlah_lagu', models.IntegerField(default=0)),
                ('total_durasi', models.IntegerField()),
                ('id_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.label')),
            ],
        ),
        migrations.CreateModel(
            name='Akun_play_User_playlist',
            fields=[
                ('waktu', models.DateTimeField(primary_key=True, serialize=False)),
                ('email_pemain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.akun')),
                ('id_User_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='user_playlist.user_playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_Konten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_playlist.konten')),
                ('total_play', models.IntegerField(default=0)),
                ('total_download', models.IntegerField(default=0)),
                ('id_Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.album')),
                ('id_Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Royalti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('id_Pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.pemilik_hak_cipta')),
                ('id_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.song')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id_Konten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_playlist.konten')),
                ('email_Podcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.podcaster')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id_episode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('durasi', models.IntegerField()),
                ('tanggal_rilis', models.DateField()),
                ('id_Konten_Podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Akun_play_Song',
            fields=[
                ('waktu', models.DateTimeField(primary_key=True, serialize=False)),
                ('email_pemain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.akun')),
                ('id_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.song')),
            ],
        ),
        migrations.CreateModel(
            name='Songwriter_write_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Songwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.songwriter')),
                ('id_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.song')),
            ],
            options={
                'unique_together': {('id_Songwriter', 'id_Song')},
            },
        ),
        migrations.CreateModel(
            name='Playlist_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.playlist')),
                ('id_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.song')),
            ],
            options={
                'unique_together': {('id_playlist', 'id_Song')},
            },
        ),
        migrations.CreateModel(
            name='Downloaded_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.premium')),
                ('id_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_playlist.song')),
            ],
            options={
                'unique_together': {('id_Song', 'email_downloader')},
            },
        ),
    ]
